'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace UserServiceReference
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="User", [Namespace]:="urn:service.tinyak.net/User/v1"),  _
     System.SerializableAttribute()>  _
    Partial Friend Class User
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailAddressField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdField As System.Nullable(Of Integer)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NameField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property EmailAddress() As String
            Get
                Return Me.EmailAddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailAddressField, value) <> true) Then
                    Me.EmailAddressField = value
                    Me.RaisePropertyChanged("EmailAddress")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property Id() As System.Nullable(Of Integer)
            Get
                Return Me.IdField
            End Get
            Set
                If (Me.IdField.Equals(value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property Name() As String
            Get
                Return Me.NameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NameField, value) <> true) Then
                    Me.NameField = value
                    Me.RaisePropertyChanged("Name")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="urn:service.tinyak.net/User/v1", ConfigurationName:="UserServiceReference.UserService")>  _
    Friend Interface UserService
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:service.tinyak.net/User/v1/UserService/Login", ReplyAction:="urn:service.tinyak.net/User/v1/UserService/LoginResponse")>  _
        Function Login(ByVal objSessionId As System.Guid, ByVal strEmailAddress As String, ByVal strPassword As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:service.tinyak.net/User/v1/UserService/IsEmailAddressAvailable", ReplyAction:="urn:service.tinyak.net/User/v1/UserService/IsEmailAddressAvailableResponse")>  _
        Function IsEmailAddressAvailable(ByVal strEmailAddress As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:service.tinyak.net/User/v1/UserService/CreateUser", ReplyAction:="urn:service.tinyak.net/User/v1/UserService/CreateUserResponse")>  _
        Function CreateUser(ByVal objSessionId As System.Guid, ByVal strName As String, ByVal strEmailAddress As String, ByVal strPassword As String) As UserServiceReference.User
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:service.tinyak.net/User/v1/UserService/GetUser", ReplyAction:="urn:service.tinyak.net/User/v1/UserService/GetUserResponse")>  _
        Function GetUser(ByVal objSessionId As System.Guid, ByVal intUserId As Integer) As UserServiceReference.User
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:service.tinyak.net/User/v1/UserService/SaveUser", ReplyAction:="urn:service.tinyak.net/User/v1/UserService/SaveUserResponse")>  _
        Function SaveUser(ByVal objSessionId As System.Guid, ByVal objUser As UserServiceReference.User) As UserServiceReference.User
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Friend Interface UserServiceChannel
        Inherits UserServiceReference.UserService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Friend Class UserServiceClient
        Inherits System.ServiceModel.ClientBase(Of UserServiceReference.UserService)
        Implements UserServiceReference.UserService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Login(ByVal objSessionId As System.Guid, ByVal strEmailAddress As String, ByVal strPassword As String) As Boolean Implements UserServiceReference.UserService.Login
            Return MyBase.Channel.Login(objSessionId, strEmailAddress, strPassword)
        End Function
        
        Public Function IsEmailAddressAvailable(ByVal strEmailAddress As String) As Boolean Implements UserServiceReference.UserService.IsEmailAddressAvailable
            Return MyBase.Channel.IsEmailAddressAvailable(strEmailAddress)
        End Function
        
        Public Function CreateUser(ByVal objSessionId As System.Guid, ByVal strName As String, ByVal strEmailAddress As String, ByVal strPassword As String) As UserServiceReference.User Implements UserServiceReference.UserService.CreateUser
            Return MyBase.Channel.CreateUser(objSessionId, strName, strEmailAddress, strPassword)
        End Function
        
        Public Function GetUser(ByVal objSessionId As System.Guid, ByVal intUserId As Integer) As UserServiceReference.User Implements UserServiceReference.UserService.GetUser
            Return MyBase.Channel.GetUser(objSessionId, intUserId)
        End Function
        
        Public Function SaveUser(ByVal objSessionId As System.Guid, ByVal objUser As UserServiceReference.User) As UserServiceReference.User Implements UserServiceReference.UserService.SaveUser
            Return MyBase.Channel.SaveUser(objSessionId, objUser)
        End Function
    End Class
End Namespace
