'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace UserServiceReference
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="urn:service.tinyak.net/User/v1", ConfigurationName:="UserServiceReference.User")>  _
    Friend Interface User
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:service.tinyak.net/User/v1/User/IsEmailAddressAvailable", ReplyAction:="urn:service.tinyak.net/User/v1/User/IsEmailAddressAvailableResponse")>  _
        Function IsEmailAddressAvailable(ByVal strEmailAddress As String) As Boolean
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Friend Interface UserChannel
        Inherits UserServiceReference.User, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Friend Class UserClient
        Inherits System.ServiceModel.ClientBase(Of UserServiceReference.User)
        Implements UserServiceReference.User
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function IsEmailAddressAvailable(ByVal strEmailAddress As String) As Boolean Implements UserServiceReference.User.IsEmailAddressAvailable
            Return MyBase.Channel.IsEmailAddressAvailable(strEmailAddress)
        End Function
    End Class
End Namespace
