'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace SessionService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Session", [Namespace]:="urn:service.tinyak.net/Session/v1"),  _
     System.SerializableAttribute()>  _
    Partial Friend Class Session
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DataField As System.Collections.Specialized.NameValueCollection
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ExpirationDateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdField As System.Guid
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserIdField As System.Nullable(Of Integer)
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property Data() As System.Collections.Specialized.NameValueCollection
            Get
                Return Me.DataField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DataField, value) <> true) Then
                    Me.DataField = value
                    Me.RaisePropertyChanged("Data")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property ExpirationDate() As Date
            Get
                Return Me.ExpirationDateField
            End Get
            Set
                If (Me.ExpirationDateField.Equals(value) <> true) Then
                    Me.ExpirationDateField = value
                    Me.RaisePropertyChanged("ExpirationDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property Id() As System.Guid
            Get
                Return Me.IdField
            End Get
            Set
                If (Me.IdField.Equals(value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Friend Property UserId() As System.Nullable(Of Integer)
            Get
                Return Me.UserIdField
            End Get
            Set
                If (Me.UserIdField.Equals(value) <> true) Then
                    Me.UserIdField = value
                    Me.RaisePropertyChanged("UserId")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="SessionService.ISessionService")>  _
    Friend Interface ISessionService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISessionService/Get", ReplyAction:="http://tempuri.org/ISessionService/GetResponse")>  _
        Function [Get](ByVal objId As System.Guid) As SessionService.Session
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISessionService/Create", ReplyAction:="http://tempuri.org/ISessionService/CreateResponse")>  _
        Function Create() As SessionService.Session
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISessionService/Save", ReplyAction:="http://tempuri.org/ISessionService/SaveResponse")>  _
        Sub Save(ByVal objSession As SessionService.Session)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Friend Interface ISessionServiceChannel
        Inherits SessionService.ISessionService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Friend Class SessionServiceClient
        Inherits System.ServiceModel.ClientBase(Of SessionService.ISessionService)
        Implements SessionService.ISessionService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function [Get](ByVal objId As System.Guid) As SessionService.Session Implements SessionService.ISessionService.[Get]
            Return MyBase.Channel.Get(objId)
        End Function
        
        Public Function Create() As SessionService.Session Implements SessionService.ISessionService.Create
            Return MyBase.Channel.Create
        End Function
        
        Public Sub Save(ByVal objSession As SessionService.Session) Implements SessionService.ISessionService.Save
            MyBase.Channel.Save(objSession)
        End Sub
    End Class
End Namespace
